### PR TITLE
routes and folders added

### LINKED ISSUE #3: setup routes and folder structure

### PR DESCRIPTION
**Pull request by Somidh**
Closes #3

### CODE REVIEW

**Review by Aadarsh805 — APPROVED** [review]
Alright good enough

**Comment by Somidh** [comment]
> Alright good enough

is landing page gonna be on that 100 page?

**Comment by Somidh** [comment]
> > Alright good enough
> 
> is landing page gonna be on that 100 page?

or needed to create a different one?

**Comment by Aadarsh805** [comment]
> > Alright good enough
> 
> is landing page gonna be on that 100 page?

No it's gonna be in the root `app/page.tsx`

**Pull request merged**
